// Convert game data kept as scripts (public/*.js, each one a single `const name = {...}`,
// generated by scraping the game's files) into the JSON files the frontend imports
// (web/data/*.json).
//
// Run from the project root:
//   node scripts/convert-data.mjs
//
// The JSON files are committed. This is only needed again if the scripts in public/ change.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import vm from 'node:vm';

/** Files converted as they are. */
const NAMES = [
    'spellData',
    'spellDataApoth',
    'wandSprites',
    'icons',
    'apothIcons',
    'pillars',
    'pillarsApoth',
    'itemData',
];

const outDir = resolve('web/data');
await mkdir(outDir, { recursive: true });

/** The value of the single top-level binding a data script declares. */
async function load(name) {
    const source = await readFile(resolve('public', `${name}.js`), 'utf8');
    // `const` does not land on the global object, so evaluate the file and then the binding's
    // name to get its value back.
    return vm.runInNewContext(`${source}\n;${name}`, {}, { filename: `${name}.js` });
}

async function write(name, value) {
    const json = JSON.stringify(value, null, 1) + '\n';
    await writeFile(resolve(outDir, `${name}.json`), json);
    const count = Array.isArray(value) ? value.length : Object.keys(value).length;
    console.log(`${name}.json  ${(json.length / 1024).toFixed(0)} KB  ${count} entries`);
}

for (const name of NAMES) await write(name, await load(name));

// spellDataMain holds the spells of the released base game, every one of which is also in
// spellData. The frontend only needs to know which spells those are, so only the ids are kept.
await write('mainSpellIds', Object.keys(await load('spellDataMain')));
